export const gamesArray = [
  {
    id: 11982,
    league: "standard",
    season: 2022,
    date: {
      start: "2023-03-02T00:00:00.000Z",
      end: null,
      duration: null,
    },
    stage: 2,
    status: {
      clock: null,
      halftime: false,
      short: 3,
      long: "Finished",
    },
    periods: {
      current: 4,
      total: 4,
      endOfPeriod: false,
    },
    arena: {
      name: "Spectrum Center",
      city: "Charlotte",
      state: "NC",
      country: null,
    },
    teams: {
      visitors: {
        id: 28,
        name: "Phoenix Suns",
        nickname: "Suns",
        code: "PHX",
        logo: "https://upload.wikimedia.org/wikipedia/fr/5/56/Phoenix_Suns_2013.png",
      },
      home: {
        id: 5,
        name: "Charlotte Hornets",
        nickname: "Hornets",
        code: "CHA",
        logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f3/Hornets_de_Charlotte_logo.svg/1200px-Hornets_de_Charlotte_logo.svg.png",
      },
    },
    scores: {
      visitors: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["27", "30", "22", "26"],
        points: 105,
      },
      home: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["22", "19", "32", "18"],
        points: 91,
      },
    },
    officials: [],
    timesTied: null,
    leadChanges: null,
    nugget: null,
  },
  {
    id: 11983,
    league: "standard",
    season: 2022,
    date: {
      start: "2023-03-02T00:00:00.000Z",
      end: null,
      duration: null,
    },
    stage: 2,
    status: {
      clock: null,
      halftime: false,
      short: 3,
      long: "Finished",
    },
    periods: {
      current: 4,
      total: 4,
      endOfPeriod: false,
    },
    arena: {
      name: "Little Caesars Arena",
      city: "Detroit",
      state: "MI",
      country: null,
    },
    teams: {
      visitors: {
        id: 6,
        name: "Chicago Bulls",
        nickname: "Bulls",
        code: "CHI",
        logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/d/d1/Bulls_de_Chicago_logo.svg/1200px-Bulls_de_Chicago_logo.svg.png",
      },
      home: {
        id: 10,
        name: "Detroit Pistons",
        nickname: "Pistons",
        code: "DET",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Detroit_Pistons_primary_logo_2017.png/150px-Detroit_Pistons_primary_logo_2017.png",
      },
    },
    scores: {
      visitors: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["38", "31", "32", "16"],
        points: 117,
      },
      home: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["36", "18", "32", "29"],
        points: 115,
      },
    },
    officials: [],
    timesTied: null,
    leadChanges: null,
    nugget: null,
  },
  {
    id: 11984,
    league: "standard",
    season: 2022,
    date: {
      start: "2023-03-02T00:30:00.000Z",
      end: null,
      duration: null,
    },
    stage: 2,
    status: {
      clock: null,
      halftime: false,
      short: 3,
      long: "Finished",
    },
    periods: {
      current: 4,
      total: 4,
      endOfPeriod: false,
    },
    arena: {
      name: "TD Garden",
      city: "Boston",
      state: "MA",
      country: null,
    },
    teams: {
      visitors: {
        id: 7,
        name: "Cleveland Cavaliers",
        nickname: "Cavaliers",
        code: "CLE",
        logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Cavs_de_Cleveland_logo_2017.png/150px-Cavs_de_Cleveland_logo_2017.png",
      },
      home: {
        id: 2,
        name: "Boston Celtics",
        nickname: "Celtics",
        code: "BOS",
        logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/6/65/Celtics_de_Boston_logo.svg/1024px-Celtics_de_Boston_logo.svg.png",
      },
    },
    scores: {
      visitors: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["28", "24", "26", "35"],
        points: 113,
      },
      home: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["26", "29", "41", "21"],
        points: 117,
      },
    },
    officials: [],
    timesTied: null,
    leadChanges: null,
    nugget: null,
  },
  {
    id: 11985,
    league: "standard",
    season: 2022,
    date: {
      start: "2023-03-02T00:30:00.000Z",
      end: null,
      duration: null,
    },
    stage: 2,
    status: {
      clock: null,
      halftime: false,
      short: 3,
      long: "Finished",
    },
    periods: {
      current: 4,
      total: 4,
      endOfPeriod: false,
    },
    arena: {
      name: "Miami-Dade Arena",
      city: "Miami",
      state: "FL",
      country: null,
    },
    teams: {
      visitors: {
        id: 27,
        name: "Philadelphia 76ers",
        nickname: "76ers",
        code: "PHI",
        logo: "https://upload.wikimedia.org/wikipedia/fr/4/48/76ers_2016.png",
      },
      home: {
        id: 20,
        name: "Miami Heat",
        nickname: "Heat",
        code: "MIA",
        logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/1/1c/Miami_Heat_-_Logo.svg/1200px-Miami_Heat_-_Logo.svg.png",
      },
    },
    scores: {
      visitors: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["34", "37", "25", "23"],
        points: 119,
      },
      home: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["38", "15", "24", "19"],
        points: 96,
      },
    },
    officials: [],
    timesTied: null,
    leadChanges: null,
    nugget: null,
  },
  {
    id: 11986,
    league: "standard",
    season: 2022,
    date: {
      start: "2023-03-02T00:30:00.000Z",
      end: null,
      duration: null,
    },
    stage: 2,
    status: {
      clock: null,
      halftime: false,
      short: 3,
      long: "Finished",
    },
    periods: {
      current: 4,
      total: 4,
      endOfPeriod: false,
    },
    arena: {
      name: "Madison Square Garden",
      city: "New York",
      state: "NY",
      country: null,
    },
    teams: {
      visitors: {
        id: 4,
        name: "Brooklyn Nets",
        nickname: "Nets",
        code: "BKN",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Brooklyn_Nets_newlogo.svg/130px-Brooklyn_Nets_newlogo.svg.png",
      },
      home: {
        id: 24,
        name: "New York Knicks",
        nickname: "Knicks",
        code: "NYK",
        logo: "https://upload.wikimedia.org/wikipedia/fr/3/34/Knicks_de_NY.png",
      },
    },
    scores: {
      visitors: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["29", "28", "30", "31"],
        points: 118,
      },
      home: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["47", "34", "29", "32"],
        points: 142,
      },
    },
    officials: [],
    timesTied: null,
    leadChanges: null,
    nugget: null,
  },
  {
    id: 11987,
    league: "standard",
    season: 2022,
    date: {
      start: "2023-03-02T01:00:00.000Z",
      end: null,
      duration: null,
    },
    stage: 2,
    status: {
      clock: null,
      halftime: false,
      short: 3,
      long: "Finished",
    },
    periods: {
      current: 4,
      total: 4,
      endOfPeriod: false,
    },
    arena: {
      name: "Toyota Center (Houston)",
      city: "Houston",
      state: "TX",
      country: null,
    },
    teams: {
      visitors: {
        id: 19,
        name: "Memphis Grizzlies",
        nickname: "Grizzlies",
        code: "MEM",
        logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Memphis_Grizzlies.svg/1200px-Memphis_Grizzlies.svg.png",
      },
      home: {
        id: 14,
        name: "Houston Rockets",
        nickname: "Rockets",
        code: "HOU",
        logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/d/de/Houston_Rockets_logo_2003.png/330px-Houston_Rockets_logo_2003.png",
      },
    },
    scores: {
      visitors: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["25", "22", "38", "28"],
        points: 113,
      },
      home: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["19", "25", "24", "31"],
        points: 99,
      },
    },
    officials: [],
    timesTied: null,
    leadChanges: null,
    nugget: null,
  },
  {
    id: 11988,
    league: "standard",
    season: 2022,
    date: {
      start: "2023-03-02T01:00:00.000Z",
      end: null,
      duration: null,
    },
    stage: 2,
    status: {
      clock: null,
      halftime: false,
      short: 3,
      long: "Finished",
    },
    periods: {
      current: 4,
      total: 4,
      endOfPeriod: false,
    },
    arena: {
      name: "Fiserv Forum",
      city: "Milwaukee",
      state: "WI",
      country: null,
    },
    teams: {
      visitors: {
        id: 26,
        name: "Orlando Magic",
        nickname: "Magic",
        code: "ORL",
        logo: "https://upload.wikimedia.org/wikipedia/fr/b/bd/Orlando_Magic_logo_2010.png",
      },
      home: {
        id: 21,
        name: "Milwaukee Bucks",
        nickname: "Bucks",
        code: "MIL",
        logo: "https://upload.wikimedia.org/wikipedia/fr/3/34/Bucks2015.png",
      },
    },
    scores: {
      visitors: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["29", "37", "30", "21"],
        points: 117,
      },
      home: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["31", "45", "32", "31"],
        points: 139,
      },
    },
    officials: [],
    timesTied: null,
    leadChanges: null,
    nugget: null,
  },
  {
    id: 11989,
    league: "standard",
    season: 2022,
    date: {
      start: "2023-03-02T01:00:00.000Z",
      end: null,
      duration: null,
    },
    stage: 2,
    status: {
      clock: null,
      halftime: false,
      short: 3,
      long: "Finished",
    },
    periods: {
      current: 4,
      total: 4,
      endOfPeriod: false,
    },
    arena: {
      name: "Paycom Center",
      city: "Oklahoma City",
      state: "OK",
      country: null,
    },
    teams: {
      visitors: {
        id: 17,
        name: "Los Angeles Lakers",
        nickname: "Lakers",
        code: "LAL",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Los_Angeles_Lakers_logo.svg/220px-Los_Angeles_Lakers_logo.svg.png",
      },
      home: {
        id: 25,
        name: "Oklahoma City Thunder",
        nickname: "Thunder",
        code: "OKC",
        logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/4/4f/Thunder_d%27Oklahoma_City_logo.svg/1200px-Thunder_d%27Oklahoma_City_logo.svg.png",
      },
    },
    scores: {
      visitors: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["31", "26", "33", "33"],
        points: 123,
      },
      home: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["30", "30", "24", "33"],
        points: 117,
      },
    },
    officials: [],
    timesTied: null,
    leadChanges: null,
    nugget: null,
  },
  {
    id: 11990,
    league: "standard",
    season: 2022,
    date: {
      start: "2023-03-02T03:00:00.000Z",
      end: null,
      duration: null,
    },
    stage: 2,
    status: {
      clock: null,
      halftime: false,
      short: 3,
      long: "Finished",
    },
    periods: {
      current: 4,
      total: 4,
      endOfPeriod: false,
    },
    arena: {
      name: "Moda Center",
      city: "Portland",
      state: "OR",
      country: null,
    },
    teams: {
      visitors: {
        id: 23,
        name: "New Orleans Pelicans",
        nickname: "Pelicans",
        code: "NOP",
        logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/2/21/New_Orleans_Pelicans.png/200px-New_Orleans_Pelicans.png",
      },
      home: {
        id: 29,
        name: "Portland Trail Blazers",
        nickname: "Trail Blazers",
        code: "POR",
        logo: "https://upload.wikimedia.org/wikipedia/en/thumb/2/21/Portland_Trail_Blazers_logo.svg/1200px-Portland_Trail_Blazers_logo.svg.png",
      },
    },
    scores: {
      visitors: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["29", "24", "37", "31"],
        points: 121,
      },
      home: {
        win: 0,
        loss: 0,
        series: {
          win: 0,
          loss: 0,
        },
        linescore: ["31", "25", "35", "19"],
        points: 110,
      },
    },
    officials: [],
    timesTied: null,
    leadChanges: null,
    nugget: null,
  },
];

//2023-03-02 boston vs cavs
export const statsArray = [
  {
    player: {
      id: 882,
      firstname: "Jayson",
      lastname: "Tatum",
    },
    team: {
      id: 2,
      name: "Boston Celtics",
      nickname: "Celtics",
      code: "BOS",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/6/65/Celtics_de_Boston_logo.svg/1024px-Celtics_de_Boston_logo.svg.png",
    },
    game: {
      id: 11984,
    },
    points: 41,
    pos: "SF",
    min: "36",
    fgm: 13,
    fga: 21,
    fgp: "61.9",
    ftm: 11,
    fta: 14,
    ftp: "78.6",
    tpm: 4,
    tpa: 6,
    tpp: "66.7",
    offReb: 2,
    defReb: 9,
    totReb: 11,
    assists: 8,
    pFouls: 1,
    steals: 0,
    turnovers: 3,
    blocks: 0,
    plusMinus: "+4",
    comment: null,
  },
  {
    player: {
      id: 248,
      firstname: "Al",
      lastname: "Horford",
    },
    team: {
      id: 2,
      name: "Boston Celtics",
      nickname: "Celtics",
      code: "BOS",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/6/65/Celtics_de_Boston_logo.svg/1024px-Celtics_de_Boston_logo.svg.png",
    },
    game: {
      id: 11984,
    },
    points: 23,
    pos: "C",
    min: "33",
    fgm: 8,
    fga: 10,
    fgp: "80.0",
    ftm: 1,
    fta: 1,
    ftp: "100.0",
    tpm: 6,
    tpa: 8,
    tpp: "75.0",
    offReb: 1,
    defReb: 10,
    totReb: 11,
    assists: 3,
    pFouls: 3,
    steals: 0,
    turnovers: 2,
    blocks: 1,
    plusMinus: "+3",
    comment: null,
  },
  {
    player: {
      id: 1045,
      firstname: "Robert",
      lastname: "Williams III",
    },
    team: {
      id: 2,
      name: "Boston Celtics",
      nickname: "Celtics",
      code: "BOS",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/6/65/Celtics_de_Boston_logo.svg/1024px-Celtics_de_Boston_logo.svg.png",
    },
    game: {
      id: 11984,
    },
    points: 11,
    pos: "C",
    min: "31",
    fgm: 4,
    fga: 4,
    fgp: "100.0",
    ftm: 3,
    fta: 3,
    ftp: "100.0",
    tpm: 0,
    tpa: 0,
    tpp: "0",
    offReb: 3,
    defReb: 8,
    totReb: 11,
    assists: 3,
    pFouls: 2,
    steals: 1,
    turnovers: 1,
    blocks: 2,
    plusMinus: "+9",
    comment: null,
  },
  {
    player: {
      id: 486,
      firstname: "Marcus",
      lastname: "Smart",
    },
    team: {
      id: 2,
      name: "Boston Celtics",
      nickname: "Celtics",
      code: "BOS",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/6/65/Celtics_de_Boston_logo.svg/1024px-Celtics_de_Boston_logo.svg.png",
    },
    game: {
      id: 11984,
    },
    points: 14,
    pos: "PG",
    min: "36",
    fgm: 3,
    fga: 11,
    fgp: "27.3",
    ftm: 6,
    fta: 8,
    ftp: "75.0",
    tpm: 2,
    tpa: 3,
    tpp: "66.7",
    offReb: 0,
    defReb: 0,
    totReb: 0,
    assists: 2,
    pFouls: 1,
    steals: 3,
    turnovers: 1,
    blocks: 0,
    plusMinus: "+1",
    comment: null,
  },
  {
    player: {
      id: 75,
      firstname: "Jaylen",
      lastname: "Brown",
    },
    team: {
      id: 2,
      name: "Boston Celtics",
      nickname: "Celtics",
      code: "BOS",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/6/65/Celtics_de_Boston_logo.svg/1024px-Celtics_de_Boston_logo.svg.png",
    },
    game: {
      id: 11984,
    },
    points: 16,
    pos: "SG",
    min: "37",
    fgm: 6,
    fga: 15,
    fgp: "40.0",
    ftm: 2,
    fta: 2,
    ftp: "100.0",
    tpm: 2,
    tpa: 5,
    tpp: "40.0",
    offReb: 0,
    defReb: 3,
    totReb: 3,
    assists: 4,
    pFouls: 3,
    steals: 0,
    turnovers: 2,
    blocks: 0,
    plusMinus: "+2",
    comment: null,
  },
  {
    player: {
      id: 2812,
      firstname: "Sam",
      lastname: "Hauser",
    },
    team: {
      id: 2,
      name: "Boston Celtics",
      nickname: "Celtics",
      code: "BOS",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/6/65/Celtics_de_Boston_logo.svg/1024px-Celtics_de_Boston_logo.svg.png",
    },
    game: {
      id: 11984,
    },
    points: 6,
    pos: "SF",
    min: "9",
    fgm: 2,
    fga: 4,
    fgp: "50.0",
    ftm: 0,
    fta: 0,
    ftp: "0",
    tpm: 2,
    tpa: 4,
    tpp: "50.0",
    offReb: 0,
    defReb: 2,
    totReb: 2,
    assists: 0,
    pFouls: 2,
    steals: 0,
    turnovers: 0,
    blocks: 0,
    plusMinus: "+1",
    comment: null,
  },
  {
    player: {
      id: 384,
      firstname: "Mike",
      lastname: "Muscala",
    },
    team: {
      id: 2,
      name: "Boston Celtics",
      nickname: "Celtics",
      code: "BOS",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/6/65/Celtics_de_Boston_logo.svg/1024px-Celtics_de_Boston_logo.svg.png",
    },
    game: {
      id: 11984,
    },
    points: 0,
    pos: "C",
    min: "11",
    fgm: 0,
    fga: 3,
    fgp: "0",
    ftm: 0,
    fta: 0,
    ftp: "0",
    tpm: 0,
    tpa: 2,
    tpp: "0",
    offReb: 0,
    defReb: 1,
    totReb: 1,
    assists: 0,
    pFouls: 2,
    steals: 0,
    turnovers: 0,
    blocks: 0,
    plusMinus: "-2",
    comment: null,
  },
  {
    player: {
      id: 71,
      firstname: "Malcolm",
      lastname: "Brogdon",
    },
    team: {
      id: 2,
      name: "Boston Celtics",
      nickname: "Celtics",
      code: "BOS",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/6/65/Celtics_de_Boston_logo.svg/1024px-Celtics_de_Boston_logo.svg.png",
    },
    game: {
      id: 11984,
    },
    points: 2,
    pos: "PG",
    min: "23",
    fgm: 1,
    fga: 5,
    fgp: "20.0",
    ftm: 0,
    fta: 0,
    ftp: "0",
    tpm: 0,
    tpa: 2,
    tpp: "0",
    offReb: 0,
    defReb: 2,
    totReb: 2,
    assists: 2,
    pFouls: 0,
    steals: 1,
    turnovers: 3,
    blocks: 0,
    plusMinus: "+3",
    comment: null,
  },
  {
    player: {
      id: 897,
      firstname: "Derrick",
      lastname: "White",
    },
    team: {
      id: 2,
      name: "Boston Celtics",
      nickname: "Celtics",
      code: "BOS",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/6/65/Celtics_de_Boston_logo.svg/1024px-Celtics_de_Boston_logo.svg.png",
    },
    game: {
      id: 11984,
    },
    points: 4,
    pos: "PG",
    min: "25",
    fgm: 2,
    fga: 5,
    fgp: "40.0",
    ftm: 0,
    fta: 0,
    ftp: "0",
    tpm: 0,
    tpa: 2,
    tpp: "0",
    offReb: 1,
    defReb: 1,
    totReb: 2,
    assists: 5,
    pFouls: 4,
    steals: 0,
    turnovers: 0,
    blocks: 1,
    plusMinus: "-1",
    comment: null,
  },
  {
    player: {
      id: 2835,
      firstname: "Evan",
      lastname: "Mobley",
    },
    team: {
      id: 7,
      name: "Cleveland Cavaliers",
      nickname: "Cavaliers",
      code: "CLE",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Cavs_de_Cleveland_logo_2017.png/150px-Cavs_de_Cleveland_logo_2017.png",
    },
    game: {
      id: 11984,
    },
    points: 12,
    pos: "PF",
    min: "39",
    fgm: 6,
    fga: 15,
    fgp: "40.0",
    ftm: 0,
    fta: 2,
    ftp: "0",
    tpm: 0,
    tpa: 2,
    tpp: "0",
    offReb: 2,
    defReb: 11,
    totReb: 13,
    assists: 1,
    pFouls: 3,
    steals: 1,
    turnovers: 0,
    blocks: 0,
    plusMinus: "-1",
    comment: null,
  },
  {
    player: {
      id: 2630,
      firstname: "Isaac",
      lastname: "Okoro",
    },
    team: {
      id: 7,
      name: "Cleveland Cavaliers",
      nickname: "Cavaliers",
      code: "CLE",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Cavs_de_Cleveland_logo_2017.png/150px-Cavs_de_Cleveland_logo_2017.png",
    },
    game: {
      id: 11984,
    },
    points: 9,
    pos: "SF",
    min: "16",
    fgm: 2,
    fga: 5,
    fgp: "40.0",
    ftm: 5,
    fta: 5,
    ftp: "100.0",
    tpm: 0,
    tpa: 3,
    tpp: "0",
    offReb: 1,
    defReb: 1,
    totReb: 2,
    assists: 0,
    pFouls: 4,
    steals: 0,
    turnovers: 0,
    blocks: 1,
    plusMinus: "-9",
    comment: null,
  },
  {
    player: {
      id: 727,
      firstname: "Jarrett",
      lastname: "Allen",
    },
    team: {
      id: 7,
      name: "Cleveland Cavaliers",
      nickname: "Cavaliers",
      code: "CLE",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Cavs_de_Cleveland_logo_2017.png/150px-Cavs_de_Cleveland_logo_2017.png",
    },
    game: {
      id: 11984,
    },
    points: 5,
    pos: "C",
    min: "39",
    fgm: 2,
    fga: 5,
    fgp: "40.0",
    ftm: 1,
    fta: 2,
    ftp: "50.0",
    tpm: 0,
    tpa: 0,
    tpp: "0",
    offReb: 2,
    defReb: 5,
    totReb: 7,
    assists: 1,
    pFouls: 1,
    steals: 3,
    turnovers: 0,
    blocks: 2,
    plusMinus: "-3",
    comment: null,
  },
  {
    player: {
      id: 1860,
      firstname: "Darius",
      lastname: "Garland",
    },
    team: {
      id: 7,
      name: "Cleveland Cavaliers",
      nickname: "Cavaliers",
      code: "CLE",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Cavs_de_Cleveland_logo_2017.png/150px-Cavs_de_Cleveland_logo_2017.png",
    },
    game: {
      id: 11984,
    },
    points: 29,
    pos: "PG",
    min: "41",
    fgm: 12,
    fga: 21,
    fgp: "57.1",
    ftm: 0,
    fta: 3,
    ftp: "0",
    tpm: 5,
    tpa: 9,
    tpp: "55.6",
    offReb: 0,
    defReb: 3,
    totReb: 3,
    assists: 9,
    pFouls: 2,
    steals: 4,
    turnovers: 4,
    blocks: 0,
    plusMinus: "+1",
    comment: null,
  },
  {
    player: {
      id: 840,
      firstname: "Donovan",
      lastname: "Mitchell",
    },
    team: {
      id: 7,
      name: "Cleveland Cavaliers",
      nickname: "Cavaliers",
      code: "CLE",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Cavs_de_Cleveland_logo_2017.png/150px-Cavs_de_Cleveland_logo_2017.png",
    },
    game: {
      id: 11984,
    },
    points: 44,
    pos: "SG",
    min: "44",
    fgm: 17,
    fga: 32,
    fgp: "53.1",
    ftm: 6,
    fta: 7,
    ftp: "85.7",
    tpm: 4,
    tpa: 12,
    tpp: "33.3",
    offReb: 1,
    defReb: 3,
    totReb: 4,
    assists: 5,
    pFouls: 4,
    steals: 0,
    turnovers: 2,
    blocks: 0,
    plusMinus: "-5",
    comment: null,
  },
  {
    player: {
      id: 2392,
      firstname: "Dean",
      lastname: "Wade",
    },
    team: {
      id: 7,
      name: "Cleveland Cavaliers",
      nickname: "Cavaliers",
      code: "CLE",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Cavs_de_Cleveland_logo_2017.png/150px-Cavs_de_Cleveland_logo_2017.png",
    },
    game: {
      id: 11984,
    },
    points: 0,
    pos: "PF",
    min: "15",
    fgm: 0,
    fga: 2,
    fgp: "0",
    ftm: 0,
    fta: 0,
    ftp: "0",
    tpm: 0,
    tpa: 2,
    tpp: "0",
    offReb: 0,
    defReb: 1,
    totReb: 1,
    assists: 0,
    pFouls: 1,
    steals: 0,
    turnovers: 0,
    blocks: 0,
    plusMinus: "-6",
    comment: null,
  },
  {
    player: {
      id: 854,
      firstname: "Cedi",
      lastname: "Osman",
    },
    team: {
      id: 7,
      name: "Cleveland Cavaliers",
      nickname: "Cavaliers",
      code: "CLE",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Cavs_de_Cleveland_logo_2017.png/150px-Cavs_de_Cleveland_logo_2017.png",
    },
    game: {
      id: 11984,
    },
    points: 0,
    pos: "SF",
    min: "5",
    fgm: 0,
    fga: 0,
    fgp: "0",
    ftm: 0,
    fta: 0,
    ftp: "0",
    tpm: 0,
    tpa: 0,
    tpp: "0",
    offReb: 0,
    defReb: 0,
    totReb: 0,
    assists: 0,
    pFouls: 0,
    steals: 0,
    turnovers: 0,
    blocks: 0,
    plusMinus: "-8",
    comment: null,
  },
  {
    player: {
      id: 459,
      firstname: "Ricky",
      lastname: "Rubio",
    },
    team: {
      id: 7,
      name: "Cleveland Cavaliers",
      nickname: "Cavaliers",
      code: "CLE",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Cavs_de_Cleveland_logo_2017.png/150px-Cavs_de_Cleveland_logo_2017.png",
    },
    game: {
      id: 11984,
    },
    points: 4,
    pos: "PG",
    min: "7",
    fgm: 1,
    fga: 1,
    fgp: "100.0",
    ftm: 1,
    fta: 2,
    ftp: "50.0",
    tpm: 1,
    tpa: 1,
    tpp: "100.0",
    offReb: 0,
    defReb: 2,
    totReb: 2,
    assists: 2,
    pFouls: 0,
    steals: 0,
    turnovers: 0,
    blocks: 0,
    plusMinus: "0",
    comment: null,
  },
  {
    player: {
      id: 317,
      firstname: "Caris",
      lastname: "LeVert",
    },
    team: {
      id: 7,
      name: "Cleveland Cavaliers",
      nickname: "Cavaliers",
      code: "CLE",
      logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Cavs_de_Cleveland_logo_2017.png/150px-Cavs_de_Cleveland_logo_2017.png",
    },
    game: {
      id: 11984,
    },
    points: 10,
    pos: "SG",
    min: "33",
    fgm: 5,
    fga: 11,
    fgp: "45.5",
    ftm: 0,
    fta: 0,
    ftp: "0",
    tpm: 0,
    tpa: 3,
    tpp: "0",
    offReb: 4,
    defReb: 2,
    totReb: 6,
    assists: 3,
    pFouls: 3,
    steals: 0,
    turnovers: 0,
    blocks: 0,
    plusMinus: "+11",
    comment: null,
  },
];
